language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
    - set -e
    - mvn clean install -Pqulice --errors --batch-mode
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8
